name: Register a domain
description: Register a new subdomain
title: "[DOMAIN]: "
labels: ["register domain"]
assignees:
  - proudparrot2
body:
  - type: markdown
    attributes:
      value: |
        Please enter your chosen domain as the issue's title, after "[DOMAIN]".
  - type: dropdown
    id: domain
    attributes:
      label: Domain
      description: What domain do you want to use?
      options:
        - isreallycool.lol 
        - mathlearning.tech 
        - sorinsurance.org 
        - artclass.site
        - hotglue.click
        - englishpapers.online
        - ixl.plus
        - sciencesimplified.pro
        - msg.boats
    validations:
      required: true
  - type: dropdown
    id: record
    attributes:
      label: Record type
      description: What is the record's type?
      options:
        - A 
        - CNAME 
        - TXT 
    validations:
      required: true

  - type: input
    id: value
    attributes:
      label: Record value
      description: What's the record's value?
      placeholder: ex. google.com
    validations:
      required: true

  - type: input
    id: txt
    attributes:
      label: Does your record need a TXT record as well?
      description: If so, enter it below. If not, leave it blank.
      placeholder: ex. site-verify=73520nc038x40m230492
    validations:
      required: false

  - type: checkboxes
    id: agree
    attributes:
      label: Code of Conduct
      description: By submitting this record, you agree to our [Registry agreements](https://github.com/sparkdns/registry/blob/main/AGREEMENTS.md)
      options:
        - label: I agree to follow the Registry agreements
          required: true
