name: Request Domain

on:
  issues:
    types: [labeled]

jobs:
  add-domain:
    if: github.event.label.name == 'add domain'
    runs-on: ubuntu-latest
    steps:
    - name: Request Domain
      id: request
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.sparkdns.io/request'
        method: 'POST'
        bearerToken: '${{ secrets.AUTHKEY }}'
        customHeaders: '{"Content-Type": "application/json"}'
        data: ${{ toJson(github.event.issue) }}
    # ${{ steps.myRequest.outputs.response }}
    
    #- name: Add comment
    #  uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
    #  with:
    #    issue-number: ${{ github.event.issue.number }}
    #    body: |
    #      Response: ${{ steps.request.outputs.response.message }}
