name: Request Domain

on:
  issues:
    types: [labeled]

jobs:
  add-domain:
    if: github.event.label.name == 'add domain'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://sparkdns-api.parrotdev.repl.co/requestdomain'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "${{ secrets.AUTHKEY }}"}'
        data: ${{ toJson(github.event.issue) }}
