name: Handle GitHub Issues

on:
  issues:
    types: [labeled]

jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
    
    - name: Issue Forms Body Parser
      id: parse
      uses: zentered/issue-forms-body-parser@v2.0.0
        
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://sparkdns-api.parrotdev.repl.co/requestdomain'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: ${{ toJSON(steps.parse.outputs.data) }}
